/**Actions */
export const REQUEST_CURRENCY = "REQUEST_CURRENCY";
export const REQUEST_SINGLE_CURRENCY = "REQUEST_SINGLE_CURRENCY";
export const SET_CURRENCY = "SET_CURRENCY";
export const REQUEST_CURRENCY_DETAILS = "REQUEST_CURRENCY_DETAILS";
export const ADD_TO_SELECT_LIST_AFTER_DELETE =
  "ADD_TO_SELECT_LIST_AFTER_DELETE";
export const ADD_BACK_TO_TABLE_FROM_SELECT = "ADD_BACK_TO_TABLE_FROM_SELECT";
export const DELETE_FROM_SELECT_LIST = "DELETE_FROM_SELECT_LIST";
export const ERROR_RECEIVED = "ERROR_RECEIVED";
